spring.application.name=tradesim

spring.data.mongodb.database=tradesim
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}
server.port=5001

tradesim.client-origin=${CLIENT_ORIGIN:http://localhost:5173}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/documentation
